# Header
menu:
  Home: /
  Info: /Info
  Donate: /Donate
rss: /atom.xml

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
 - tagcloud
 - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: /favicon.png

node_sass:
  debug: false
  outputStyle: nested
  precision: 5
  sourceComments: false